version: '3.9'

services:
  db:
      image: postgres:16
      container_name: db
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ports:
        - 5432:5432
      networks:
        - djangonetwork


  backend:
      build:
        context: ./source
      command: >
        bash -c "python manage.py makemigrations && 
                 python manage.py migrate && 
                 python manage.py create_doctor_group && 
                 python manage.py loaddata /app/db_dump.json &&
                 python manage.py collectstatic --noinput &&
                 python manage.py runserver 0.0.0.0:8001"
      ports:
        - 8001:8001
      depends_on:
        - db
      env_file:
        - source/.env
      environment:
        DATABASE_HOST: ${POSTGRES_HOST}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      volumes:
        - ./staticfiles:/main/staticfiles
        - ./source/uploads:/var/www/media
      links:
        - db:db
      networks:
        - djangonetwork

volumes:
  postgres_data:
    driver: local

networks:
  djangonetwork:
    driver: bridge
