# Generated by Django 5.1.5 on 2025-01-25 21:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате: 996779339944', regex='^996\\d{3}\\d{2}\\d{2}\\d{2}$')], verbose_name='Номер телефона'),
        ),
    ]
